### ISSUE TITLE
Make workspace private

### ISSUE THREAD

**Issue by duncanfwalker** [CampaignLab/gotv-dashboard#2]
Should be private but accessible by sharing a link - creates space, just used for single election

- Later may be useful to access data from past elections for same area
- Space can be any region you’re campaigning in with some number of polling stations
- Should probably have a start and end time so that its only writable (at least by volunteers) on the day.

**Comment by bobwhitelock** [comment]
I've made each WorkSpace effectively private (or at least secret only to those it is shared with), but went down a different route for doing this than a shared password emailed to the person who creates the WorkSpace (which I gather was your current plan). See https://github.com/CampaignLab/gotv-dashboard/commit/8787374c43105a9decfc436d8682e4633f2bf75a for the main commit making this change and explanation of the approach, and why I thought this was OK/sufficient at least for the MVP. Let me know if you have any concerns with this approach and I can add to or change it.

I think that completes this issue sufficiently for our MVP, but I'll split out separate tasks for the possible future extensions you mention that we can come back to if/when needed.
