### ISSUE TITLE
Add volunteer details (name) against each observation

### ISSUE THREAD

**Issue by duncanfwalker** [CampaignLab/gotv-dashboard#3]
Think mainly benefits the committee room - if they can identify the source of each observation it will be easier for them to make corrections and clarifications with the volunteers. 

Phone number and display name could be sufficient for that.

We probably don't want to do anything that increases the friction for a volunteer sending their first observation so I'm imagining that they can send without setting any of their details and are offer the opportunity to add their details afterward. 

Even if they don't share there details we probably still want an ID like a session ID against each observation so we can more easily ignore bogus ones if we get them.

**Comment by bobwhitelock** [comment]
Plan for how this should work from meeting the other day:

- Associate and display session ID alongside each observation made by each individual User

- After recording an observation, a volunteer is then prompted and (optionally) able to associate a name and phone number with their session ID

- Once this has been done after any observation, this name + phone number will also be displayed alongside their observations and they will no longer be prompted for this after future observations

(Also: I noticed you'd listed this as in progress @duncanfwalker, but assume you've not done anything on this yet as I can't see anything in the codebase, and so I've moved it to better track what needs doing for Thursday - apologies and let me know if this was incorrect though).

**Comment by duncanfwalker** [comment]
That's right not done any code yet
