### ISSUE TITLE
Up-front data input by organiser of registered voters and Labour Promises

### ISSUE THREAD

**Issue by duncanfwalker** [CampaignLab/gotv-dashboard#5]

**Comment by duncanfwalker** [comment]
Maybe this should be split into 1) registered voters and 2) promises to make sure we can get the first one finished?

**Comment by bobwhitelock** [comment]
Think we'll want to move the `pre_election_*` fields to the `PollingStation`/`WorkSpace` join table for this, to have somewhere to store this data per-WorkSpace. This would also involve adding a specific model for this table, and possibly also renaming the table something more descriptive for this concept.

**Comment by bobwhitelock** [comment]
As with https://github.com/CampaignLab/gotv-dashboard/issues/3: noticed you'd listed this as in progress @duncanfwalker, but assume you've not done anything on this yet as I can't see anything in the codebase, and so I've moved it to better track what needs doing for Thursday - apologies and let me know if this was incorrect though.

**Comment by bobwhitelock** [comment]
Hold off for now, maybe import from Contact Creator report
